name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST_ORACLE }}
                  USERNAME: ${{ secrets.USERNAME_ORACLE }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY_ORACLE }}
                  command_timeout: 200m
                  script: 'cd infinity-website-backend && git reset --hard && git pull && npm i && npm run build && pm2 restart infinity-backend'
